server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaservice-container:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: universityservice
          uri: lb://universityservice
          predicates:
            - Path=/universities/**
          filters:
            - AuthFilter
        - id: teacherservice
          uri: lb://teacherservice
          predicates:
            - Path=/teachers/**
        - id: studentservice
          uri: lb://studentservice
          predicates:
            - Path=/students/**
        - id: authservice
          uri: lb://authservice
          predicates:
            - Path=/auth/**
            
            