server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: resilence4j
          uri: https://github.com/brunotarditi/Microservices
          search-paths: config-data
  application:
    name: config-service