server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: docker
          uri: https://github.com/brunotarditi/Microservices
          search-paths: config-data
  application:
    name: configservice